                
                <h2>{TITLE}<h2> 
                <blockquote>{MESSAGE}</blockquote>        
                -----------------------------------
                
                {SUBMESSAGE}
                -----------------------------------
                <a href="{LINK}" target="_blank" >the link to click</a>
                OR
                {LINK}
                ========================================
                This message was generated by Dollop CMS